### PR TITLE
feat: Gnome 45 Support

### LINKED ISSUE #19: gnome 45
Gnome 45 has some changes to imports because of the new js version

### PR DESCRIPTION
**Pull request by BlankParticle**
# Changes
- Gnome 45 Support
- Preferences Widget
- Clean ups, build scripts, formatter
- Drop `Gtk` as dependency and replace with custom `RecentManager`
- Don't List deleted files/directories 

Fixes: #19

### CODE REVIEW

**Comment by BlankParticle** [comment]
The PR is not yet ready, 
We need to reimplement `Gtk.RecentManager` as it is now forbidden to import `Gtk` in shell process. I am working on a replacement already.

**Comment by BlankParticle** [comment]
@bananenfisch, This PR is almost ready to be merged, do some testing on your machine before merging. 
I tested on mine, works fine.

**Comment by bananenfisch** [comment]
Thank you!
Debian unstable is still on gnome 44 :-/ So i cannot test it now on my machine - but it looks good. Thanks also for the settings task! :)

**Comment by molitona** [comment]
@BlankParticle could u find a solution to get it work for gnome 46 ?

**Comment by BlankParticle** [comment]
> @BlankParticle could u find a solution to get it work for gnome 46 ?

it should be easy as opening the manifest file and adding 46 to supported version. Nothing major was changed and should work.
Report your finding, if it doesn't work I will take a look.

**Comment by molitona** [comment]
> > @BlankParticle could u find a solution to get it work for gnome 46 ?
> 
> it should be easy as opening the manifest file and adding 46 to supported version. Nothing major was changed and should work. Report your finding, if it doesn't work I will take a look.

did that already and not work

**Pull request merged**
